version: '3.1'

services:
  couvertown:
    container_name: 'couvertown'
    build: ./client
    ports:
      - '3000'
    networks:
      - docker-network

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    links:
      - couvertown
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./secrets/certbot/conf:/etc/letsencrypt:ro
      - ./secrets/certbot/www:/var/www/certbot:ro
      - ./secrets/dhparam.pem:/etc/dhparam.pem:ro
    networks:
      - docker-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./secrets/certbot/conf:/etc/letsencrypt
      - ./secrets/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  docker-network:
    driver: bridge
