version: '3.1'

services:
  couvertown:
    container_name: 'couvertown'
    build: .
    ports:
      - '3000'
    networks:
      - docker-network

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    links:
      - couvertown
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
